Revert comments

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,82 +36,82 @@ jobs:
           path: dist
           retention-days: 1
 
-#   cli_test:
-#     name: CLI test (Python ${{ matrix.python-version }})
-#     needs: build
-#     runs-on: ubuntu-20.04
-#     strategy:
-#       matrix:
-#         python-version:
-#           - "3.8"
-#           - "3.9"
-#     steps:
-#       - uses: actions/checkout@v2
+  cli_test:
+    name: CLI test (Python ${{ matrix.python-version }})
+    needs: build
+    runs-on: ubuntu-20.04
+    strategy:
+      matrix:
+        python-version:
+          - "3.8"
+          - "3.9"
+    steps:
+      - uses: actions/checkout@v2
 
-#       - name: Set up Python
-#         uses: actions/setup-python@v2
-#         with:
-#           python-version: ${{ matrix.python-version }}
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python-version }}
 
-#       - name: Download build distributable
-#         uses: actions/download-artifact@v2
-#         with:
-#           name: distributable
+      - name: Download build distributable
+        uses: actions/download-artifact@v2
+        with:
+          name: distributable
 
-#       - name: CLI test
-#         run: |
-#           pip install wev
-#           pip install "$(ls *.whl)"
+      - name: CLI test
+        run: |
+          pip install wev
+          pip install "$(ls *.whl)"
 
-#           export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
-#           export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
+          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
+          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
 
-#           cd functional-test
+          cd functional-test
 
-#           cp Pipfile.template Pipfile
-#           echo "python_version = \"${{ matrix.python-version }}\"" >> Pipfile
+          cp Pipfile.template Pipfile
+          echo "python_version = \"${{ matrix.python-version }}\"" >> Pipfile
 
-#           # Install pipenv
-#           pip install --upgrade pip
-#           pip install pipenv
+          # Install pipenv
+          pip install --upgrade pip
+          pip install pipenv
 
-#           # Assert that "tupper" is not yet installed, so we can later confirm
-#           # that we definitely pulled via an authorisation token.
-#           set +e
-#           pipenv run python -m tupper
-#           returned=$?
-#           set -e
-#           if [[ "${returned}" != "1" ]]; then
-#             echo "Expected tupper execution to fail gracefully: ${returned}"
-#             exit 1
-#           fi
+          # Assert that "tupper" is not yet installed, so we can later confirm
+          # that we definitely pulled via an authorisation token.
+          set +e
+          pipenv run python -m tupper
+          returned=$?
+          set -e
+          if [[ "${returned}" != "1" ]]; then
+            echo "Expected tupper execution to fail gracefully: ${returned}"
+            exit 1
+          fi
 
-#           # Install our Pipfile (i.e. install "tupper") via wev.
-#           wev pipenv install --skip-lock
+          # Install our Pipfile (i.e. install "tupper") via wev.
+          wev pipenv install --skip-lock
 
-#           # Assert that we just pulled "tupper".
-#           pipenv run python -m tupper
+          # Assert that we just pulled "tupper".
+          pipenv run python -m tupper
 
-#   publish_to_pypi:
-#     if: startsWith(github.ref, 'refs/tags')
-#     needs: cli_test
-#     runs-on: ubuntu-20.04
-#     steps:
-#       - name: Download build distributable
-#         uses: actions/download-artifact@v2
-#         with:
-#           name: distributable
-#           path: dist
+  publish_to_pypi:
+    if: startsWith(github.ref, 'refs/tags')
+    needs: cli_test
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Download build distributable
+        uses: actions/download-artifact@v2
+        with:
+          name: distributable
+          path: dist
 
-#       - name: Publish
-#         uses: pypa/gh-action-pypi-publish@v1.4.1
-#         with:
-#           user: __token__
-#           password: ${{ secrets.PYPI_TOKEN }}
+      - name: Publish
+        uses: pypa/gh-action-pypi-publish@v1.4.1
+        with:
+          user: __token__
+          password: ${{ secrets.PYPI_TOKEN }}
 
   publish_to_github:
-    # if: startsWith(github.ref, 'refs/tags')
-    needs: build  # cli_test
+    if: startsWith(github.ref, 'refs/tags')
+    needs: cli_test
     runs-on: ubuntu-20.04
     steps:
       - name: Download build distributable
@@ -120,24 +120,20 @@ jobs:
         with:
           name: distributable
 
-      - run: |
-          echo "DISTRIBUTABLE=$(ls *.whl)"
-          echo "DISTRIBUTABLE=$(ls *.whl)" >> $GITHUB_ENV
+      - run: echo "DISTRIBUTABLE=$(ls *.whl)" >> $GITHUB_ENV
 
-      - run: echo "${{ env.DISTRIBUTABLE }}"
+      - name: Get release
+        id: get_release
+        uses: bruceadams/get-release@v1.2.2
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
 
-    #   - name: Get release
-    #     id: get_release
-    #     uses: bruceadams/get-release@v1.2.2
-    #     env:
-    #       GITHUB_TOKEN: ${{ github.token }}
-
-    #   - name: Publish
-    #     uses: actions/upload-release-asset@v1
-    #     env:
-    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-    #     with:
-    #       upload_url: ${{ steps.get_release.outputs.upload_url }}
-    #       asset_path: ${{ env.DISTRIBUTABLE }}
-    #       asset_name: my-artifact.zip
-    #       asset_content_type: application/zip
+      - name: Publish
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.get_release.outputs.upload_url }}
+          asset_path: ${{ env.DISTRIBUTABLE }}
+          asset_name: wev-awscodeartifact.whl
+          asset_content_type: application/x-wheel+zip
